// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Json = require("./json.bs.js");
var Path = require("path");
var Parse = require("./parse.bs.js");
var Convert = require("./convert.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var basepath = "aws-sdk-js-v3/codegen/sdk-codegen/aws-models";

var files = Fs.readdirSync(basepath);

Belt_Array.forEach(files, (function (file) {
        var path = Path.join(basepath, file);
        console.log("Reading " + path);
        var parsed = Json.Decode.parseJson(Fs.readFileSync(path, undefined).toString(), Parse.parseModel);
        var generated;
        generated = parsed.TAG === /* Ok */0 ? Convert.convert({
                TAG: /* Ok */0,
                _0: parsed._0
              }) : ({
              TAG: /* Error */1,
              _0: Json.Decode.jsonParseErrorToString(parsed._0)
            });
        if (generated.TAG === /* Ok */0) {
          var match = generated._0;
          var moduleName = match.moduleName;
          console.log("Writing module", moduleName);
          Fs.writeFileSync("src/generated/aws/" + moduleName + ".res", Buffer.from(match.code));
          return ;
        }
        console.log("Unable to generate for file " + file + ": " + generated._0);
        
      }));

exports.basepath = basepath;
exports.files = files;
/* files Not a pure module */
