// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Util = require("./util.bs.js");
var Trait = require("./trait.bs.js");
var Js_option = require("rescript/lib/js/js_option.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

function safeMemberName(name) {
  switch (name) {
    case "Type" :
    case "type" :
        return "type_";
    default:
      return name.charAt(0).toLowerCase() + name.slice(1);
  }
}

function safeTypeName(target) {
  var name = Util.symbolName(target);
  var namespace = Util.symbolNamespace(target);
  var namespacePrefix = Belt_Option.getWithDefault(Belt_Array.get(namespace.split("."), 1), "");
  switch (name) {
    case "Bool" :
        return namespacePrefix + "Bool";
    case "Boolean" :
        return namespacePrefix + "Boolean";
    case "Double" :
        return namespacePrefix + "Double";
    case "Integer" :
        return namespacePrefix + "Integer";
    case "Long" :
        return namespacePrefix + "Long";
    case "String" :
        return namespacePrefix + "String";
    case "Timestamp" :
        return namespacePrefix + "Timestamp";
    case "Export" :
    case "export" :
        return "export_";
    case "Type" :
    case "type" :
        return "type_";
    case "Unit" :
    case "unit" :
        return "unit_";
    default:
      return name.charAt(0).toLowerCase() + name.slice(1);
  }
}

function safeConstructorName(name) {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

function safeVariantName(name) {
  return name.replace(new RegExp("-|#|:|\\.", "g"), "_");
}

function generateIntegerShape(name) {
  return "type " + safeTypeName(name) + " = int;";
}

function generateLongShape(name) {
  return "type " + safeTypeName(name) + " = float;";
}

function generateDoubleShape(name) {
  return "type " + safeTypeName(name) + " = float;";
}

function generateFloatShape(name) {
  return "type " + safeTypeName(name) + " = float;";
}

function generateBooleanShape(name) {
  return "type " + safeTypeName(name) + " = bool;";
}

function generateBinaryShape(name) {
  return "type " + safeTypeName(name) + " = NodeJs.Buffer.t;";
}

function generateStringShape(name, details) {
  var enumTrait = Js_option.map((function (traits) {
          return Caml_option.undefined_to_opt(traits.find(Trait.isEnumTrait));
        }), details.traits);
  if (enumTrait !== undefined) {
    var match = Caml_option.valFromOption(enumTrait);
    if (match !== undefined && typeof match !== "number" && match.TAG === /* EnumTrait */8) {
      var $$enum = Belt_Array.map(match._0, (function (pair) {
              return "@as(\"" + pair.value + "\")" + " #" + safeVariantName(pair.value);
            }));
      return "type " + safeTypeName(name) + " = [" + Belt_Array.joinWith($$enum, " | ", (function (x) {
                    return x;
                  })) + "]";
    }
    
  }
  return "type " + safeTypeName(name) + " = string";
}

function generateMember(m) {
  var required = Trait.hasTrait(m.traits, Trait.isRequiredTrait);
  return "@as(\"" + m.name + "\") " + safeMemberName(m.name) + ": " + (
          required ? "option<" + safeTypeName(m.target) + ">" : safeTypeName(m.target)
        );
}

function indentString(indent) {
  var is = [];
  Belt_Array.fill(is, 0, indent, " ");
  return Belt_Array.joinWith(is, "", (function (x) {
                return x;
              }));
}

function generateStructureShape(name, details, indentOpt, param) {
  var indent = indentOpt !== undefined ? indentOpt : 0;
  var is = indentString(indent);
  var memberStrings = Belt_Array.map(details.members, (function (member) {
          return is + indentString(2) + generateMember(member);
        }));
  var isError = Trait.hasTrait(details.traits, Trait.isErrorTrait);
  if (isError) {
    return "exception " + safeConstructorName(Util.symbolName(name)) + ";";
  } else {
    return is + "type " + safeTypeName(name) + " = " + (
            memberStrings.length === 0 ? "unit" : "{\n" + Belt_Array.joinWith(memberStrings, ",\n", (function (x) {
                      return x;
                    })) + "\n" + is + "}"
          );
  }
}

function generateUnionMember(param) {
  return safeConstructorName(param.name) + "(" + safeTypeName(param.target) + ")";
}

function generateUnionShape(name, details) {
  var memberStrings = Belt_Array.map(details.members, generateUnionMember);
  return "type " + safeTypeName(name) + " = " + Belt_Array.joinWith(memberStrings, " | ", (function (x) {
                return x;
              })) + ";";
}

function generateListShape(name, target) {
  return "type " + safeTypeName(name) + " = array<" + safeTypeName(target) + ">";
}

function generateMapShape(name, param, mapValue) {
  var valueType = safeTypeName(mapValue.target);
  return "type " + safeTypeName(name) + " = Js.Dict.t< " + valueType + ">";
}

var NoServiceTrait = /* @__PURE__ */Caml_exceptions.create("Generate.NoServiceTrait");

function generateServiceShape(serviceName, traits) {
  var match = Trait.findTrait(traits, Trait.isAwsApiServiceTrait);
  if (match !== undefined && !(typeof match === "number" || match.TAG !== /* ServiceTrait */3)) {
    return "type clientType;\n@module(\"@aws-sdk/client-" + serviceName + "\") @new external createClient: unit => clientType = \"" + match._0.cloudFormationName + "Client\";";
  } else {
    return "";
  }
}

function generateSetShape(name, details) {
  return "type " + safeTypeName(name) + " = array<" + safeTypeName(details.target) + ">";
}

var UnknownTimestampFormat = /* @__PURE__ */Caml_exceptions.create("Generate.UnknownTimestampFormat");

function generateTimestampShape(name, param) {
  var timestampFormat = Trait.findTrait(Belt_Option.getWithDefault(param.traits, []), Trait.isTimestampFormatTrait);
  var typeName = safeTypeName(name);
  if (timestampFormat !== undefined && typeof timestampFormat !== "number" && timestampFormat.TAG === /* TimestampFormatTrait */12) {
    switch (timestampFormat._0) {
      case "date-time" :
          return "type " + typeName + " = Js.Date.t;";
      case "epoch-seconds" :
          return "type " + typeName + " = int;";
      default:
        
    }
  }
  return "type " + typeName + " = Js.Date.t;";
}

function generateOperationStructureType(varName, opStruct) {
  if (typeof opStruct === "number") {
    return "";
  } else if (opStruct.TAG === /* OperationStructure */0) {
    return generateStructureShape("#" + varName, opStruct._0, 2, undefined);
  } else {
    return "type " + varName + " = " + safeTypeName(opStruct._0) + ";";
  }
}

function isOperationStructureNone(opStruct) {
  if (typeof opStruct === "number") {
    return true;
  } else {
    return false;
  }
}

function generateOperationModule(moduleName, param) {
  var output = param[2];
  var input = param[1];
  var name = param[0];
  var commandName = Util.symbolName(name) + "Command";
  var request = generateOperationStructureType("request", input);
  var response = generateOperationStructureType("response", output);
  var inputType = isOperationStructureNone(input) ? "Js.Promise.t<unit>" : "Js.Promise.t<request>";
  var outputType = isOperationStructureNone(output) ? "Js.Promise.t<unit>" : "Js.Promise.t<response>";
  return "module " + Util.symbolName(name) + " = {\n" + "  type t;\n" + ("  " + request + "\n") + ("  " + response + "\n") + ("  @module(\"@aws-sdk/client-" + moduleName + "\") @new external new_: (" + inputType + ") => t = \"" + commandName + "\";\n") + ("  @send external send: (clientType, t) => " + outputType + " = \"send\";\n") + "}\n";
}

function generateTypeBlock(serviceName, param) {
  var descriptor = param.descriptor;
  var name = param.name;
  if (typeof descriptor === "number") {
    if (descriptor === /* BlobShape */0) {
      return generateBinaryShape(name);
    } else {
      return "";
    }
  }
  switch (descriptor.TAG | 0) {
    case /* ListShape */0 :
        return generateListShape(name, descriptor._0.target);
    case /* OperationShape */1 :
        return "";
    case /* StructureShape */2 :
        return generateStructureShape(name, descriptor._0, undefined, undefined);
    case /* UnionShape */3 :
        return generateUnionShape(name, descriptor._0);
    case /* ServiceShape */4 :
        return generateServiceShape(serviceName, descriptor._0.traits);
    case /* BooleanShape */5 :
        return generateBooleanShape(name);
    case /* IntegerShape */6 :
        return generateIntegerShape(name);
    case /* StringShape */7 :
        return generateStringShape(name, descriptor._0);
    case /* MapShape */8 :
        var details = descriptor._0;
        return generateMapShape(name, details.mapKey, details.mapValue);
    case /* TimestampShape */9 :
        return generateTimestampShape(name, descriptor._0);
    case /* LongShape */10 :
        return generateLongShape(name);
    case /* FloatShape */11 :
        return generateFloatShape(name);
    case /* DoubleShape */12 :
        return generateDoubleShape(name);
    case /* SetShape */13 :
        return generateSetShape(name, descriptor._0);
    
  }
}

exports.safeMemberName = safeMemberName;
exports.safeTypeName = safeTypeName;
exports.safeConstructorName = safeConstructorName;
exports.safeVariantName = safeVariantName;
exports.generateIntegerShape = generateIntegerShape;
exports.generateLongShape = generateLongShape;
exports.generateDoubleShape = generateDoubleShape;
exports.generateFloatShape = generateFloatShape;
exports.generateBooleanShape = generateBooleanShape;
exports.generateBinaryShape = generateBinaryShape;
exports.generateStringShape = generateStringShape;
exports.generateMember = generateMember;
exports.indentString = indentString;
exports.generateStructureShape = generateStructureShape;
exports.generateUnionMember = generateUnionMember;
exports.generateUnionShape = generateUnionShape;
exports.generateListShape = generateListShape;
exports.generateMapShape = generateMapShape;
exports.NoServiceTrait = NoServiceTrait;
exports.generateServiceShape = generateServiceShape;
exports.generateSetShape = generateSetShape;
exports.UnknownTimestampFormat = UnknownTimestampFormat;
exports.generateTimestampShape = generateTimestampShape;
exports.generateOperationStructureType = generateOperationStructureType;
exports.isOperationStructureNone = isOperationStructureNone;
exports.generateOperationModule = generateOperationModule;
exports.generateTypeBlock = generateTypeBlock;
/* No side effect */
