// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Parse_api = require("./parse_api.bs.js");

var parsed = Parse_api.parse("aws-sdk-js-v3/codegen/sdk-codegen/aws-models/sqs.2012-11-05.json");

if (parsed.TAG === /* Ok */0) {
  console.log(parsed._0);
} else {
  console.log("error", parsed._0);
}

exports.parsed = parsed;
/* parsed Not a pure module */
