// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("rescript/lib/js/js_option.js");
var Parse_api = require("./parse_api.bs.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

var parsed = Parse_api.parse("aws-sdk-js-v3/codegen/sdk-codegen/aws-models/sqs.2012-11-05.json");

function getTargets(shape) {
  switch (shape.TAG | 0) {
    case /* ListShape */0 :
        return [shape._1.target];
    case /* OperationShape */1 :
        var details = shape._1;
        return [details.input].concat(Js_option.getWithDefault([], Belt_Option.map(details.output, (function (extracted) {
                              return [extracted];
                            }))));
    case /* StructureShape */2 :
        return shape._1.members.map(function (member) {
                    return member.target;
                  });
    case /* ServiceShape */3 :
        return shape._1.operations.map(function (operation) {
                    return operation;
                  });
    case /* MapShape */8 :
        var match = shape._1;
        return [
                match.mapKey.target,
                match.mapValue.target
              ];
    default:
      return [];
  }
}

function order(shapes) {
  var targets = shapes.map(getTargets);
  console.log(targets);
  
}

if (parsed.TAG === /* Ok */0) {
  order(parsed._0);
} else {
  console.log("error", parsed._0);
}

exports.parsed = parsed;
exports.getTargets = getTargets;
exports.order = order;
/* parsed Not a pure module */
