// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function isServiceShape(shape) {
  if (typeof shape === "number" || shape.TAG !== /* ServiceShape */4) {
    return false;
  } else {
    return true;
  }
}

exports.isServiceShape = isServiceShape;
/* No side effect */
