// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var UnsupportedOperation = /* @__PURE__ */Caml_exceptions.create("Sqs.UnsupportedOperation");

var TooManyEntriesInBatchRequest = /* @__PURE__ */Caml_exceptions.create("Sqs.TooManyEntriesInBatchRequest");

var ReceiptHandleIsInvalid = /* @__PURE__ */Caml_exceptions.create("Sqs.ReceiptHandleIsInvalid");

var QueueNameExists = /* @__PURE__ */Caml_exceptions.create("Sqs.QueueNameExists");

var QueueDoesNotExist = /* @__PURE__ */Caml_exceptions.create("Sqs.QueueDoesNotExist");

var QueueDeletedRecently = /* @__PURE__ */Caml_exceptions.create("Sqs.QueueDeletedRecently");

var PurgeQueueInProgress = /* @__PURE__ */Caml_exceptions.create("Sqs.PurgeQueueInProgress");

var OverLimit = /* @__PURE__ */Caml_exceptions.create("Sqs.OverLimit");

var MessageNotInflight = /* @__PURE__ */Caml_exceptions.create("Sqs.MessageNotInflight");

var InvalidMessageContents = /* @__PURE__ */Caml_exceptions.create("Sqs.InvalidMessageContents");

var InvalidIdFormat = /* @__PURE__ */Caml_exceptions.create("Sqs.InvalidIdFormat");

var InvalidBatchEntryId = /* @__PURE__ */Caml_exceptions.create("Sqs.InvalidBatchEntryId");

var InvalidAttributeName = /* @__PURE__ */Caml_exceptions.create("Sqs.InvalidAttributeName");

var EmptyBatchRequest = /* @__PURE__ */Caml_exceptions.create("Sqs.EmptyBatchRequest");

var BatchRequestTooLong = /* @__PURE__ */Caml_exceptions.create("Sqs.BatchRequestTooLong");

var BatchEntryIdsNotDistinct = /* @__PURE__ */Caml_exceptions.create("Sqs.BatchEntryIdsNotDistinct");

var RemovePermission = {};

var PurgeQueue = {};

var GetQueueUrl = {};

var DeleteQueue = {};

var DeleteMessage = {};

var ChangeMessageVisibility = {};

var UntagQueue = {};

var TagQueue = {};

var SetQueueAttributes = {};

var ListQueues = {};

var ListQueueTags = {};

var ListDeadLetterSourceQueues = {};

var GetQueueAttributes = {};

var CreateQueue = {};

var AddPermission = {};

var DeleteMessageBatch = {};

var ChangeMessageVisibilityBatch = {};

var SendMessage = {};

var SendMessageBatch = {};

var ReceiveMessage = {};

exports.UnsupportedOperation = UnsupportedOperation;
exports.TooManyEntriesInBatchRequest = TooManyEntriesInBatchRequest;
exports.ReceiptHandleIsInvalid = ReceiptHandleIsInvalid;
exports.QueueNameExists = QueueNameExists;
exports.QueueDoesNotExist = QueueDoesNotExist;
exports.QueueDeletedRecently = QueueDeletedRecently;
exports.PurgeQueueInProgress = PurgeQueueInProgress;
exports.OverLimit = OverLimit;
exports.MessageNotInflight = MessageNotInflight;
exports.InvalidMessageContents = InvalidMessageContents;
exports.InvalidIdFormat = InvalidIdFormat;
exports.InvalidBatchEntryId = InvalidBatchEntryId;
exports.InvalidAttributeName = InvalidAttributeName;
exports.EmptyBatchRequest = EmptyBatchRequest;
exports.BatchRequestTooLong = BatchRequestTooLong;
exports.BatchEntryIdsNotDistinct = BatchEntryIdsNotDistinct;
exports.RemovePermission = RemovePermission;
exports.PurgeQueue = PurgeQueue;
exports.GetQueueUrl = GetQueueUrl;
exports.DeleteQueue = DeleteQueue;
exports.DeleteMessage = DeleteMessage;
exports.ChangeMessageVisibility = ChangeMessageVisibility;
exports.UntagQueue = UntagQueue;
exports.TagQueue = TagQueue;
exports.SetQueueAttributes = SetQueueAttributes;
exports.ListQueues = ListQueues;
exports.ListQueueTags = ListQueueTags;
exports.ListDeadLetterSourceQueues = ListDeadLetterSourceQueues;
exports.GetQueueAttributes = GetQueueAttributes;
exports.CreateQueue = CreateQueue;
exports.AddPermission = AddPermission;
exports.DeleteMessageBatch = DeleteMessageBatch;
exports.ChangeMessageVisibilityBatch = ChangeMessageVisibilityBatch;
exports.SendMessage = SendMessage;
exports.SendMessageBatch = SendMessageBatch;
exports.ReceiveMessage = ReceiveMessage;
/* No side effect */
