// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Js_option = require("rescript/lib/js/js_option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function isEnumTrait(trait) {
  if (typeof trait === "number" || trait.TAG !== /* EnumTrait */8) {
    return false;
  } else {
    return true;
  }
}

function isRequiredTrait(trait) {
  return trait === 0;
}

function isErrorTrait(trait) {
  if (typeof trait === "number" || trait.TAG !== /* ErrorTrait */1) {
    return false;
  } else {
    return true;
  }
}

function isAwsApiServiceTrait(trait) {
  if (typeof trait === "number" || trait.TAG !== /* ServiceTrait */3) {
    return false;
  } else {
    return true;
  }
}

function isTimestampFormatTrait(trait) {
  if (typeof trait === "number" || trait.TAG !== /* TimestampFormatTrait */12) {
    return false;
  } else {
    return true;
  }
}

function hasTrait(traitsOption, traitTest) {
  return Js_option.getWithDefault(false, Js_option.map((function (traits) {
                    return traits.some(Curry.__1(traitTest));
                  }), traitsOption));
}

function findTrait(traits, traitsTest) {
  return Caml_option.undefined_to_opt(traits.find(Curry.__1(traitsTest)));
}

exports.isEnumTrait = isEnumTrait;
exports.isRequiredTrait = isRequiredTrait;
exports.isErrorTrait = isErrorTrait;
exports.isAwsApiServiceTrait = isAwsApiServiceTrait;
exports.isTimestampFormatTrait = isTimestampFormatTrait;
exports.hasTrait = hasTrait;
exports.findTrait = findTrait;
/* No side effect */
