// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");

function symbolName(str) {
  var result = Belt_Array.get(str.split("#"), 1);
  return Belt_Option.getWithDefault(result, str);
}

function symbolNamespace(str) {
  var result = Belt_Array.get(str.split("#"), 0);
  return Belt_Option.getWithDefault(result, "");
}

exports.symbolName = symbolName;
exports.symbolNamespace = symbolNamespace;
/* No side effect */
