// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");

function symbolName(str) {
  return Caml_array.get(str.split("#"), 1);
}

function symbolNamespace(str) {
  return Caml_array.get(str.split("#"), 0);
}

exports.symbolName = symbolName;
exports.symbolNamespace = symbolNamespace;
/* No side effect */
